### ISSUE TITLE
Docs example of kube-helmi.yaml contains errors

### ISSUE THREAD

**Issue by hkroger** [monostream/helmi#18]
Hi,

I am looking into using kube-helmi and I found out that the `docs/kubernetes/kube-helmi.yaml` does not work as-is.

First problem is that readinessProbe is using `kubectl` and for some reason it is not found. Maybe it is run inside the container or something?

Second problem is that there is no catalog in the config and the image contains apparently no catalog in the default location. So adding 

    name: CATALOG_URL
    value: https://abc/xyz/catalog.zip

is mandatory in `env`.

**Comment by adrianliechti** [comment]
thank you super much. you are totally right - we run it in a container where this exists. we also use the catalog url for all of our own installations.

the whole process how we setup helmi is automatized and does not compare to the sample deployments anymore :/

we should fix that.

i will create a story in our internal team backlog to fix the sample and standalone installation

**Comment by hkroger** [comment]
Merci vielmals!

Should we keep this issue open until that is fixed and released?

**Comment by adrianliechti** [comment]
sure. i keep you updated

**Comment by munzli** [comment]
- the yaml example has been updated (note that this is only a little helper)
- and not setting CATALOG_URL should default to the local `./catalog` folder
