### ISSUE TITLE
Optionally clear out PVCs after deletion

### ISSUE THREAD

**Issue by hkroger** [monostream/helmi#21]
Helm and Kubernetes work that way that PVCs created by statefulsets are left in place after deletion of the release. 

It would be great to have that functionality in Helmi so that if catalog item contains some specific parameter, then deletion of the release would also trigger deletion of the PVC so that PV can be also deleted. Using labels release=helmi-xyz would probably work here.

Does this make sense to you?

**Comment by adrianliechti** [comment]
I see...

hmmm... one could think about different approaches
- wait for kubernetes (https://github.com/kubernetes/kubernetes/issues/55045)
- add this feature to helm (helm delete {relese} --delete-pvc (and make sure the reclaimpolicy is set) 
- add something like an external garbage collector (not in helmi)
- extend helmi to do such life cycle jobs... (with kubernetes tasks, or an mq)
- let's talk about offering you a custom-made solution

**Comment by hkroger** [comment]
I guess the right thing to wait for the kubernetes ticket to be resolved. Meanwhile we can live with manual or non-helmi specific garbage collection, I think. Thanks!
