### ISSUE TITLE
Docker Container starts after a very long time.

### ISSUE THREAD

**Issue by kazz-s** [monostream/helmi#43]
When https://kubernetes-charts.storage.googleapis.com is not reachable it takes helmi way to long to start since timeout during `helm repo update` is high.

I propose to remove stable repo by default.

**Comment by adrianliechti** [comment]
i see...

we could checkin the .helm folder in this repo and just add it to the image. so the "helm init" is not needed, and the startup is faster

**Comment by hkroger** [comment]
In our case, we use helmi behind a firewall with no access to official chart repos, so we also remove the default stable repo when we build our image.

**Comment by adrianliechti** [comment]
I created a small pull request  #44.
let me know what you think. cheers

**Comment by adrianliechti** [comment]
you should see new latest & stable tags
https://cloud.docker.com/u/monostream/repository/docker/monostream/helmi/tags

let me know any succeed or fail with these. cheers :)

**Comment by kazz-s** [comment]
Now it fails with:

kubectl logs helmi-5c8b84cd85-czj56
2019/06/08 14:29:41 failed to update repository datapipelines: Error: open /home/helmi/.helm/repository/repositories.yaml: permission denied
