### ISSUE TITLE
catalog model, can't convert some field to correct value

### ISSUE THREAD

**Issue by wdxxs2z** [monostream/helmi#6]
Hi,

  In UserCredentials function, i found some user-credentials fields can't convert to correct value(notice no value), such as the catalog: rabbitmq, like this  .Values.rabbitmq.username, but if i define it like .Values.something , the tamplate can parse it.

  The cause may be the varValues is map[string]string, like  key is "rabbitmq.username", but the template read .Values.rabbitmq.username may Values -> rabbitmq -> username type

**Comment by adrianliechti** [comment]
thank you! we will have a look this week and further improve the catalog template engine

cheers

**Comment by gandro** [comment]
I started working on a fix in the [`nested-values`](https://github.com/monostream/helmi/tree/nested-values) branch. The current version just removes the flattening of helms output, but I think the `chart-values` yaml section also needs a refactor to see how nested values can be properly supported.

**Comment by wdxxs2z** [comment]
Maybe, we can use "github.com/smallfish/simpleyaml" package,  when we get all the values of a release from helm, it should be the yaml format, and then whether we can convert them directly to the map[interface{}]interface{}, and finally fill the template.

Or convert the string that has been converted to json directly into a map[interface{}]interface{}, and then fill in the template.
